version: "3.8"

services:
  nextjs:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    command: npm run start  # Starts the app in production mode
    ports:
      - "3000:3000"